# Generated by Django 4.1.3 on 2022-11-11 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='choices',
            new_name='choice',
        ),
    ]
